Traceback (most recent call last):
  File "gquench_cluster.py", line 67, in <module>
    os.mkdir(datapath)
FileExistsError: [Errno 17] File exists: '/n/regal/demler_lab/kis/VariationalResearch/genPolaron/clusterdata/aIBi_4.00/NGridPoints_4.00E+04'
